#!/usr/bin/env python

ergodoxian = (
("KEY_DeleteBackspace","1x2"),
("KEY_DeleteForward","1x2"),
('KEY_ReturnEnter', '1x2'),
('KEY_Spacebar', '1x2'),
('SPECIAL_Fn', '1x2'),
('KEY_Shift', '1.5x1'),
('KEY_Shift', '1.5x1'),
("KEY_Dash_Underscore", "1.5x1"),
("KEY_Equal_Plus", "1.5x1"),
('KEY_ReturnEnter', '1.5x1'),
("KEY_Escape", "1.5x1"),
("KEY_DeleteForward","1.5x1"),
('SPECIAL_Fn', '1x1.5'),
("KEY_LeftBracket_LeftBrace", "1x1.5"),
("KEY_RightBracket_RightBrace", "1x1.5"),
("KEY_SingleQuote_DoubleQuote", "1.5x1"),
("KEY_GraveAccent_Tilde", "1.5x1"),
("KEY_Slash_Question", "1.5x1"),
("KEY_Tab","1x1.5"))

new1 = (
("KEY_DeleteBackspace","1x2"),
("KEY_DeleteForward","1x2"),
('KEY_ReturnEnter', '1x2'),
('KEY_Spacebar', '1x2'),
('SPECIAL_Fn', '1x2'),
('KEY_Shift', '1.5x1'),
('KEY_Shift', '1.5x1'),
("KEY_Dash_Underscore", "1.5x1"),
("KEY_Equal_Plus", "1.5x1"),
('KEY_ReturnEnter', '1.5x1'),
("KEY_Escape", "1.5x1"),
("KEY_DeleteForward","1.5x1"),
('SPECIAL_Fn', '1x1.5'),
("KEY_LeftBracket_LeftBrace", "1x1.5"),
("KEY_RightBracket_RightBrace", "1x1.5"),
("KEY_SingleQuote_DoubleQuote", "1.5x1"),
("KEY_GraveAccent_Tilde", "1.5x1"),
("KEY_Slash_Question", "1.5x1"),
('SPECIAL_Fn', '1x1.5'))

new2 = (
('KEY_Shift', '1x2'),
("KEY_DeleteForward","1x2"),
('KEY_ReturnEnter', '1x2'),
('KEY_Spacebar', '1x2'),
('SPECIAL_Fn', '1x2'),
('KEY_Shift', '1.5x1'),
('KEY_Shift', '1.5x1'),
("KEY_Dash_Underscore", "1.5x1"),
("KEY_Equal_Plus", "1.5x1"),
('KEY_ReturnEnter', '1.5x1'),
("KEY_Escape", "1.5x1"),
("KEY_DeleteForward","1.5x1"),
('SPECIAL_Fn', '1x1.5'),
("KEY_LeftBracket_LeftBrace", "1x1.5"),
("KEY_RightBracket_RightBrace", "1x1.5"),
("KEY_SingleQuote_DoubleQuote", "1.5x1"),
("KEY_GraveAccent_Tilde", "1.5x1"),
("KEY_Slash_Question", "1.5x1"),
('KEY_Tab', '1x1.5'))

new3 = (
('KEY_Shift', '1x2'),
("KEY_DeleteForward","1x2"),
('KEY_ReturnEnter', '1x2'),
('KEY_Spacebar', '1x2'),
('SPECIAL_Fn', '1x2'),
('KEY_Shift', '1.5x1'),
('KEY_Shift', '1.5x1'),
("KEY_Dash_Underscore", "1.5x1"),
("KEY_Equal_Plus", "1.5x1"),
('KEY_ReturnEnter', '1.5x1'),
("KEY_Escape", "1.5x1"),
("KEY_DeleteForward","1.5x1"),
('SPECIAL_Fn', '1x1.5'),
("KEY_LeftBracket_LeftBrace", "1x1.5"),
("KEY_RightBracket_RightBrace", "1x1.5"),
("KEY_SingleQuote_DoubleQuote", "1.5x1"),
("KEY_GraveAccent_Tilde", "1.5x1"),
("KEY_Slash_Question", "1.5x1"),
('SPECIAL_Fn', '1x1.5'))

suggested1 = map(lambda k: (k[1],k[0]), (
('1x2', 'KEY_Shift'),
('1x2', 'KEY_DeleteForward'),
('1x2', 'KEY_Spacebar'),
('1x2', 'KEY_Spacebar'),
('1x2', 'SPECIAL_Fn'),
('1.5x1', 'KEY_Shift'),
('1.5x1', 'KEY_Shift'),
('1.5x1', 'KEY_Dash_Underscore'),
('1.5x1', 'KEY_Equal_Plus'),
('1x1.5', 'KEY_ReturnEnter'),
('1.5x1', 'KEY_Escape'),
('1x1.5', 'KEY_DeleteForward'),
('1x1.5', 'SPECIAL_Fn'),
('1x1.5', 'KEY_LeftBracket_LeftBrace'),
('1x1.5', 'KEY_RightBracket_RightBrace'),
('1.5x1', 'KEY_SingleQuote_DoubleQuote'),
('1.5x1', 'KEY_GraveAccent_Tilde'),
('1.5x1', 'KEY_Slash_Question'),
('1x1.5', 'SPECIAL_Fn')
))

suggested2 = map(lambda k: (k[1],k[0]), (
('1x2', 'KEY_Shift'),
('1x2', 'KEY_DeleteForward'),
('1x2', 'KEY_Spacebar'),
('1x2', 'KEY_Spacebar'),
('1x2', 'SPECIAL_Fn'),
('1.5x1', 'KEY_Shift'),
('1.5x1', 'KEY_Shift'),
('1.5x1', 'KEY_Dash_Underscore'),
('1.5x1', 'KEY_Equal_Plus'),
('1.5x1', 'KEY_ReturnEnter'),
('1.5x1', 'KEY_Escape'),
('1x1.5', 'KEY_DeleteForward'),
('1x1.5', 'SPECIAL_Fn'),
('1x1.5', 'KEY_LeftBracket_LeftBrace'),
('1x1.5', 'KEY_RightBracket_RightBrace'),
('1.5x1', 'KEY_SingleQuote_DoubleQuote'),
('1.5x1', 'KEY_GraveAccent_Tilde'),
('1.5x1', 'KEY_Slash_Question'),
('1x2', 'SPECIAL_Fn'),
))

hof = (ergodoxian, new1, new2, new3, suggested1, suggested2)
